[build]
  command = "bash prebuild.sh && npm run build"
  publish = "dist"
  functions = "netlify/functions"

  [build.environment]
    NODE_ENV = "production"
    FIREBASE_PROJECT = "trs-operator-live"
    NETLIFY_AUTH_TOKEN = "your_token_if_using_netlify_cli"
